apiVersion: v1
kind: Service
metadata:
  name: django
  labels:
    app: django
spec:
  ports:
    - port: 8000
  selector:
    app: django
    tier: app
  type: LoadBalancer

---

apiVersion: v1
kind:PersistentVolumeClaim
metadata:
  name: django-app-pvc
  labels:
    app: django
spec:
  accessMode:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
  labels:
    app:django
    tier: app
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        app: django
        tier: app
    spec:
      volume:
        - name: django-app-data
          persistentVolumeClai:
            claimName: django-app-pvc
      containers:
        - image: django-app:latest
          imagePullPolicy: Never
          name: app
          volumeMount:
            - name: django-app-data
              mountPath: /vol/web
          env:
            - name: DB_HOST
              value: django-postgres
            - name: DB_NAME
              value: djangodb
            - name: DB_USER
              value: djangouser
            - name: ALLOWED_HOSTS
              value: '127.0.0.1, localhost'
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-password
                  key: password
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: django
                  key: secret
        - image: django-proxy:latest
          imagePullPolicy: Nevername: proxy
          ports:
            - containerPort: 8000
              name: proxy
          volumeMounts:
            - name: django-app-data
              mountPath: /vol/web
          env:
            - name: APP_HOST
              value: '127.0.0.1'
            - name: APP_PORT
              value: 8080


